### ISSUE TITLE
iSH Shell

### ISSUE THREAD

**Issue by gijdeme** [ItzBlinkzy/prntscraper#1]
Hi. I couldn't set it up in iSH Shell, on my iPhone, please help.

**Comment by ItzBlinkzy** [comment]
I'll try to add compatibility for the ish shell.

**Comment by ItzBlinkzy** [comment]
I'll try to add compatibility for the iSH Shell.

**Comment by gijdeme** [comment]
We'll be very glad, thank you.

**Comment by ItzBlinkzy** [comment]
Okay so I added it. Things you have to do in iSH are : 
 ## 1
 ```bash
apk add python3-pip
```
 ## 2
```bash
pip3 install prntscraper
```
 ## 3
```bash
mkdir /images
```
 ## 4
   * **Once that is finished downloading run `python` in the shell and import the module in a similar way shown in the [README.md](https://github.com/ItzBlinkzy/prntscraper/blob/master/README.md)**

At this point you are now able to store images in the folder `/images` with the module, however at the moment **I am not sure if it's possible to open any of the images with iSH yet** but I'll try to find out and see.

**Comment by ItzBlinkzy** [comment]
Any problems let me know

**Comment by gijdeme** [comment]
I did everything, but I don't know how to run to upload a photo 🤷🏻‍♂️

**Comment by ItzBlinkzy** [comment]
So unfortunately you are not able to retrieve the photos that are downloaded in iSH Shell.
