### ISSUE TITLE
no longer working?

### ISSUE THREAD

**Issue by yashma052** [ItzBlinkzy/prntscraper#11]
Greetings.  When will the code be updated?  how do you know the characters have become sensitive, is it possible to bypass this?

**Comment by ItzBlinkzy** [comment]
Hello, I've tested the module recently and it seems to work fine. Can you please specify what you want to be updated?

**Comment by yashma052** [comment]
> Hello, I've tested the module recently and it seems to work fine. Can you please specify what you want to be updated?

if you notice, the links are no longer **6** or **7** digits, they have become long and **sensitive**, example: https://prnt.sc/**cE5wM2nhc8VM**

**Comment by ItzBlinkzy** [comment]
Thanks for notifying me about this. I've uploaded some test images and it seems like the new links are completely random
and not efficiently scrapable with a bot. This means I won't be able to update the bot to this new system. However, you are still able to download previous images prior to https://prnt.sc updating the links.

**Comment by ItzBlinkzy** [comment]
https://github.com/ItzBlinkzy/prntscraper/blob/ecd0ec3c950fe80ff3b7dd7a9f2520c2e4b0dd05/prntscraper/scraper.py#L77.
I will be removing the (newest) parameter In the next update due to this change.

**Comment by yashma052** [comment]
> Thanks for notifying me about this. I've uploaded some test images and it seems like the new links are completely random
> 
> and not efficiently scrapable with a bot. This means I won't be able to update the bot to this new system. However, you are still able to download previous images prior to https://prnt.sc updating the links.

thanks man, good luck with your project.
