### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by emezelenme** [ItzBlinkzy/prntscraper#12]
![Import Error](https://user-images.githubusercontent.com/97851087/207597000-aedc5591-845e-4624-bcee-6526c04ba96c.png)

Hello, how to solve this problem? And what is the correct way to launch it?

**Comment by ItzBlinkzy** [comment]
Hello, all you have to do is **rename** your file to anything else other than `prntscraper.py`, as this is confusing for the python interpreter.
