### ISSUE TITLE
Doesn't seem to create images folder

### ISSUE THREAD

**Issue by stefastra** [ItzBlinkzy/prntscraper#13]
the python script file is on my desktop but there is no images folder being created, is neither in the c:/Python310 nor the desktop. Also, when creating the folder manually it does not fill with images
![image](https://github.com/ItzBlinkzy/prntscraper/assets/46135339/3527e400-1ce5-4a16-84c9-1cbba4e33bca)

**Comment by ItzBlinkzy** [comment]
Please take a closer look in your desktop directory. I just tested on multiple devices and there seems to be no issue with images being scraped and stored in the images folder.

Also if you're 100% sure that a `./images` folder was not created, then you can create the folder in the same directory you are running the python script and the images will be stored there.

**Comment by stefastra** [comment]
It does indeed work after all, the ./images folder was created in C:\Users (where the terminal was running) rather than the desktop (where the script file was)
