### ISSUE TITLE
Need help installing

### ISSUE THREAD

**Issue by cprichin** [ItzBlinkzy/prntscraper#4]
I'm being really stupid and have absolutely no clue what i need to do, how would I set this up and be able to use it?

**Comment by Lexumiii** [comment]
Hey, 

maybe I can help. 

1. Install [Python ](https://www.python.org/ ), [pip](https://pypi.org/project/pip/) and [Chromedriver](https://chromedriver.chromium.org/downloads) if you have not already.
2. make sure everything is installed and added to your System path variables.
3. Open a text document and paste the code that is in the README under "How to use".
4. Save the file as "prntscraper.py".
5. Open CMD and type "pip install prntscraper".  -> Wait for it to finish
6. Create a folder named "images" in the folder in which the file is in.
7. Open CMD again and redirect into it with "cd [PATH]"
8. Type "python prntscraper.py" and hit enter.

I hope this works for you, if any error occurs, just write a comment here. 
The developer of this tool seems not very active.

Greetings 
Lexumi
