### ISSUE TITLE
HOW TO INSTALL ON WINDOWS?

### ISSUE THREAD

**Issue by emezelenme** [ItzBlinkzy/prntscraper#8]
Hello. Please explain step by step how to install on Windows 11, I can't. And print.scrn has already removed 7 digit characters, now in the form of "**vAVidwq3YjRC**", will there be a solution for this?

**Comment by ItzBlinkzy** [comment]
The installation process should be the same for Windows 10 as both versions are very similar. Windows 11 is backwards compatible so you should have no problem following the installation instructions on a Windows 11 system. As for the 7 digit character problem, I am finding a way to bypass this but thanks for bringing it to my attention.

**Comment by emezelenme** [comment]
> The installation process should be the same for Windows 10 as both versions are very similar. Windows 11 is backwards compatible so you should have no problem following the installation instructions on a Windows 11 system. As for the 7 digit character problem, I am finding a way to bypass this but thanks for bringing it to my attention.

Thanks for the help.

I hope you can get around this problem. Because it is impossible to define a screenshot with this format PqAg0964vLhR
