### ISSUE TITLE
Speeding up the code

### ISSUE THREAD

**Issue by icdmkg2** [ItzBlinkzy/prntscraper#9]
Is there a way to speed the code up ?

**Comment by ItzBlinkzy** [comment]
Unfortunately not, when you do speed up the requests, they begin to get rate-limited and begin to error.
However a temporary solution that works from time to time is using threads.


**You will need to pip install `pynput` to enter the amount of images that you want for each thread**
```py
import threading
from pynput.keyboard import Key, Controller
from prntscraper import PrntScraper

keyboard = Controller()
def get_images():
    print(PrntScraper().get_random_images())


threads = []
for i in range(0, 10):
    t = threading.Thread(target=get_images)
    threads.append(t)
    t.start()


for i in range(0, 10):
    keyboard.type("10") # change this to how much images you want each thread to fetch
    keyboard.press(Key.enter)
```

![image](https://user-images.githubusercontent.com/68260779/158233259-98d1f967-1e88-4456-b8d3-1a6140bd1879.png)
At the moment it seems to work fine, if you encounter any issues, please let me know.

**Comment by ItzBlinkzy** [comment]
**Additional note**: Doing this a lot will probably get your IP rate-limited quickly and you won't be able to download any images for a short while.

**Comment by icdmkg2** [comment]
Thats not a problem and there sure is a way to integrate proxies with the code

**Comment by icdmkg2** [comment]
Yea that happend 
![image](https://user-images.githubusercontent.com/87490651/158238084-832ad3dd-fd44-45e6-b146-3360275d85e5.png)
